# Generated by Django 5.0.6 on 2024-06-20 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': (('can_import_users', 'Can import users'), ('can_export_users', 'Can export users'), ('can_view_phone', 'Can view phone field'), ('can_edit_phone', 'Can edit phone field'))},
        ),
    ]
