# Generated by Django 5.0.7 on 2024-07-31 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=60, unique=True)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('V', 'V'), ('NV', 'NV'), ('B', 'B')], default='V', max_length=2)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_name', to='user.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
