# Generated by Django 5.0.7 on 2024-07-31 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='type',
            field=models.CharField(choices=[('V', 'Vegeterian'), ('NV', 'Non Vegeterian'), ('B', 'Both')], default='V', max_length=2),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=100)),
                ('image_url', models.ImageField(upload_to='restaurant')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_image', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
