# Generated by Django 5.0.7 on 2024-08-01 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_menu_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='category',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='is_veg',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='item_name',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='price',
        ),
        migrations.AlterField(
            model_name='menu',
            name='restaurant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rest_name', to='restaurant.restaurant'),
        ),
    ]
