# Generated by Django 5.0.7 on 2024-08-01 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_rename_category_menu_name_remove_menu_is_veg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.CharField(max_length=50)),
                ('is_veg', models.BooleanField(default=True)),
                ('item_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_name', to='restaurant.menu')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
