# Generated by Django 5.0.7 on 2024-08-01 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_alter_menuitems_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('O', 'Owner'), ('S', 'Staff')], default='C', max_length=1)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(db_index=True, max_length=60, unique=True)),
                ('password', models.TextField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_profile', to='restaurant.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
