# Generated by Django 5.0.7 on 2024-08-01 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_alter_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='desination',
            field=models.CharField(choices=[('S', 'Sweeper'), ('CH', 'Chef'), ('W', 'Waiter'), ('CA', 'Cashier'), ('RM', 'Restaurant Manager'), ('DW', 'Dishwasher'), ('SG', 'Security Guard')], default='RM', max_length=3),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='M', max_length=1, null=True),
        ),
    ]
