# Generated by Django 5.0.7 on 2024-08-01 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_profile_desination_alter_profile_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='desination',
            new_name='designation',
        ),
    ]
