# Generated by Django 5.0.7 on 2024-08-01 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0014_alter_table_table_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitems',
            name='menu',
        ),
    ]
