# Generated by Django 5.0.7 on 2024-08-01 10:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0015_remove_menuitems_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_menuitems', to='restaurant.menu'),
        ),
    ]
