# Generated by Django 5.0.7 on 2024-08-01 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0016_menuitems_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitems',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menuitems', to='restaurant.menu'),
        ),
    ]
